[package]
name = "multicore-proj"
version = "0.1.0"
authors = ["ruoyi <endvroy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"